name: NoteIt Test on Pipeline

on:
  pull_request:
    branch: [ master ]
  schedule:
    - cron: '*/5 * * 1-5'

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Instalar Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Run test
        run: mvn test
